### ISSUE TITLE
🗺 Create Map Component 🗺

### ISSUE THREAD

**Issue by damla** [damla/karsal#88]
# Cheat Sheet

- https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker#getpitchalignment
- Coordinates
   - 🏢 HQ: 28.656831, 40.990484
   - 🏭 Factory: 27.649564, 41.272214

# To-Do

- [x] Create a map component.
- [x] Refactor component according to needs.
- [x] Implement component to Contact [#75] page.
- [x] Connect content to db.
